[project]
name = "phoice"
version = "0.1.0"
description = "Ultra simple transcription"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.1.1",
    "pyaudio>=0.2.14",
    "pynput>=1.8.1",
    "pyperclip>=1.9.0",
]
